# Generated by Django 2.2.1 on 2019-05-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='Subject',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
