from setuptools import setup

setup(
    name='web_builder',
    version='1.0',
    packages=['core', 'core.migrations', 'crud', 'crud.migrations', 'venv.Lib.site-packages.PIL',
              'venv.Lib.site-packages.attr', 'venv.Lib.site-packages.idna', 'venv.Lib.site-packages.pytz',
              'venv.Lib.site-packages.zope.interface', 'venv.Lib.site-packages.zope.interface.tests',
              'venv.Lib.site-packages.zope.interface.common', 'venv.Lib.site-packages.zope.interface.common.tests',
              'venv.Lib.site-packages.django', 'venv.Lib.site-packages.django.db',
              'venv.Lib.site-packages.django.db.models', 'venv.Lib.site-packages.django.db.models.sql',
              'venv.Lib.site-packages.django.db.models.fields', 'venv.Lib.site-packages.django.db.models.functions',
              'venv.Lib.site-packages.django.db.backends', 'venv.Lib.site-packages.django.db.backends.base',
              'venv.Lib.site-packages.django.db.backends.dummy', 'venv.Lib.site-packages.django.db.backends.mysql',
              'venv.Lib.site-packages.django.db.backends.oracle', 'venv.Lib.site-packages.django.db.backends.sqlite3',
              'venv.Lib.site-packages.django.db.backends.postgresql',
              'venv.Lib.site-packages.django.db.backends.postgresql_psycopg2',
              'venv.Lib.site-packages.django.db.migrations', 'venv.Lib.site-packages.django.db.migrations.operations',
              'venv.Lib.site-packages.django.apps', 'venv.Lib.site-packages.django.conf',
              'venv.Lib.site-packages.django.conf.urls', 'venv.Lib.site-packages.django.conf.locale',
              'venv.Lib.site-packages.django.conf.locale.ar', 'venv.Lib.site-packages.django.conf.locale.az',
              'venv.Lib.site-packages.django.conf.locale.bg', 'venv.Lib.site-packages.django.conf.locale.bn',
              'venv.Lib.site-packages.django.conf.locale.bs', 'venv.Lib.site-packages.django.conf.locale.ca',
              'venv.Lib.site-packages.django.conf.locale.cs', 'venv.Lib.site-packages.django.conf.locale.cy',
              'venv.Lib.site-packages.django.conf.locale.da', 'venv.Lib.site-packages.django.conf.locale.de',
              'venv.Lib.site-packages.django.conf.locale.el', 'venv.Lib.site-packages.django.conf.locale.en',
              'venv.Lib.site-packages.django.conf.locale.eo', 'venv.Lib.site-packages.django.conf.locale.es',
              'venv.Lib.site-packages.django.conf.locale.et', 'venv.Lib.site-packages.django.conf.locale.eu',
              'venv.Lib.site-packages.django.conf.locale.fa', 'venv.Lib.site-packages.django.conf.locale.fi',
              'venv.Lib.site-packages.django.conf.locale.fr', 'venv.Lib.site-packages.django.conf.locale.fy',
              'venv.Lib.site-packages.django.conf.locale.ga', 'venv.Lib.site-packages.django.conf.locale.gd',
              'venv.Lib.site-packages.django.conf.locale.gl', 'venv.Lib.site-packages.django.conf.locale.he',
              'venv.Lib.site-packages.django.conf.locale.hi', 'venv.Lib.site-packages.django.conf.locale.hr',
              'venv.Lib.site-packages.django.conf.locale.hu', 'venv.Lib.site-packages.django.conf.locale.id',
              'venv.Lib.site-packages.django.conf.locale.is', 'venv.Lib.site-packages.django.conf.locale.it',
              'venv.Lib.site-packages.django.conf.locale.ja', 'venv.Lib.site-packages.django.conf.locale.ka',
              'venv.Lib.site-packages.django.conf.locale.km', 'venv.Lib.site-packages.django.conf.locale.kn',
              'venv.Lib.site-packages.django.conf.locale.ko', 'venv.Lib.site-packages.django.conf.locale.lt',
              'venv.Lib.site-packages.django.conf.locale.lv', 'venv.Lib.site-packages.django.conf.locale.mk',
              'venv.Lib.site-packages.django.conf.locale.ml', 'venv.Lib.site-packages.django.conf.locale.mn',
              'venv.Lib.site-packages.django.conf.locale.nb', 'venv.Lib.site-packages.django.conf.locale.nl',
              'venv.Lib.site-packages.django.conf.locale.nn', 'venv.Lib.site-packages.django.conf.locale.pl',
              'venv.Lib.site-packages.django.conf.locale.pt', 'venv.Lib.site-packages.django.conf.locale.ro',
              'venv.Lib.site-packages.django.conf.locale.ru', 'venv.Lib.site-packages.django.conf.locale.sk',
              'venv.Lib.site-packages.django.conf.locale.sl', 'venv.Lib.site-packages.django.conf.locale.sq',
              'venv.Lib.site-packages.django.conf.locale.sr', 'venv.Lib.site-packages.django.conf.locale.sv',
              'venv.Lib.site-packages.django.conf.locale.ta', 'venv.Lib.site-packages.django.conf.locale.te',
              'venv.Lib.site-packages.django.conf.locale.th', 'venv.Lib.site-packages.django.conf.locale.tr',
              'venv.Lib.site-packages.django.conf.locale.uk', 'venv.Lib.site-packages.django.conf.locale.vi',
              'venv.Lib.site-packages.django.conf.locale.de_CH', 'venv.Lib.site-packages.django.conf.locale.en_AU',
              'venv.Lib.site-packages.django.conf.locale.en_GB', 'venv.Lib.site-packages.django.conf.locale.es_AR',
              'venv.Lib.site-packages.django.conf.locale.es_CO', 'venv.Lib.site-packages.django.conf.locale.es_MX',
              'venv.Lib.site-packages.django.conf.locale.es_NI', 'venv.Lib.site-packages.django.conf.locale.es_PR',
              'venv.Lib.site-packages.django.conf.locale.pt_BR', 'venv.Lib.site-packages.django.conf.locale.sr_Latn',
              'venv.Lib.site-packages.django.conf.locale.zh_Hans', 'venv.Lib.site-packages.django.conf.locale.zh_Hant',
              'venv.Lib.site-packages.django.core', 'venv.Lib.site-packages.django.core.mail',
              'venv.Lib.site-packages.django.core.mail.backends', 'venv.Lib.site-packages.django.core.cache',
              'venv.Lib.site-packages.django.core.cache.backends', 'venv.Lib.site-packages.django.core.files',
              'venv.Lib.site-packages.django.core.checks', 'venv.Lib.site-packages.django.core.checks.security',
              'venv.Lib.site-packages.django.core.checks.compatibility', 'venv.Lib.site-packages.django.core.servers',
              'venv.Lib.site-packages.django.core.handlers', 'venv.Lib.site-packages.django.core.management',
              'venv.Lib.site-packages.django.core.serializers', 'venv.Lib.site-packages.django.http',
              'venv.Lib.site-packages.django.test', 'venv.Lib.site-packages.django.urls',
              'venv.Lib.site-packages.django.forms', 'venv.Lib.site-packages.django.utils',
              'venv.Lib.site-packages.django.utils.translation', 'venv.Lib.site-packages.django.views',
              'venv.Lib.site-packages.django.views.generic', 'venv.Lib.site-packages.django.views.decorators',
              'venv.Lib.site-packages.django.contrib', 'venv.Lib.site-packages.django.contrib.gis',
              'venv.Lib.site-packages.django.contrib.gis.db', 'venv.Lib.site-packages.django.contrib.gis.db.models',
              'venv.Lib.site-packages.django.contrib.gis.db.models.sql',
              'venv.Lib.site-packages.django.contrib.gis.db.backends',
              'venv.Lib.site-packages.django.contrib.gis.db.backends.base',
              'venv.Lib.site-packages.django.contrib.gis.db.backends.mysql',
              'venv.Lib.site-packages.django.contrib.gis.db.backends.oracle',
              'venv.Lib.site-packages.django.contrib.gis.db.backends.postgis',
              'venv.Lib.site-packages.django.contrib.gis.db.backends.spatialite',
              'venv.Lib.site-packages.django.contrib.gis.gdal', 'venv.Lib.site-packages.django.contrib.gis.gdal.raster',
              'venv.Lib.site-packages.django.contrib.gis.gdal.prototypes',
              'venv.Lib.site-packages.django.contrib.gis.geos',
              'venv.Lib.site-packages.django.contrib.gis.geos.prototypes',
              'venv.Lib.site-packages.django.contrib.gis.admin', 'venv.Lib.site-packages.django.contrib.gis.forms',
              'venv.Lib.site-packages.django.contrib.gis.utils', 'venv.Lib.site-packages.django.contrib.gis.geoip2',
              'venv.Lib.site-packages.django.contrib.gis.sitemaps',
              'venv.Lib.site-packages.django.contrib.gis.serializers', 'venv.Lib.site-packages.django.contrib.auth',
              'venv.Lib.site-packages.django.contrib.auth.handlers',
              'venv.Lib.site-packages.django.contrib.auth.management',
              'venv.Lib.site-packages.django.contrib.auth.migrations', 'venv.Lib.site-packages.django.contrib.admin',
              'venv.Lib.site-packages.django.contrib.admin.views',
              'venv.Lib.site-packages.django.contrib.admin.migrations',
              'venv.Lib.site-packages.django.contrib.admin.templatetags', 'venv.Lib.site-packages.django.contrib.sites',
              'venv.Lib.site-packages.django.contrib.sites.migrations',
              'venv.Lib.site-packages.django.contrib.humanize',
              'venv.Lib.site-packages.django.contrib.humanize.templatetags',
              'venv.Lib.site-packages.django.contrib.messages',
              'venv.Lib.site-packages.django.contrib.messages.storage',
              'venv.Lib.site-packages.django.contrib.postgres', 'venv.Lib.site-packages.django.contrib.postgres.forms',
              'venv.Lib.site-packages.django.contrib.postgres.fields',
              'venv.Lib.site-packages.django.contrib.postgres.aggregates',
              'venv.Lib.site-packages.django.contrib.sessions',
              'venv.Lib.site-packages.django.contrib.sessions.backends',
              'venv.Lib.site-packages.django.contrib.sessions.migrations',
              'venv.Lib.site-packages.django.contrib.sitemaps', 'venv.Lib.site-packages.django.contrib.admindocs',
              'venv.Lib.site-packages.django.contrib.flatpages',
              'venv.Lib.site-packages.django.contrib.flatpages.migrations',
              'venv.Lib.site-packages.django.contrib.flatpages.templatetags',
              'venv.Lib.site-packages.django.contrib.redirects',
              'venv.Lib.site-packages.django.contrib.redirects.migrations',
              'venv.Lib.site-packages.django.contrib.staticfiles',
              'venv.Lib.site-packages.django.contrib.staticfiles.templatetags',
              'venv.Lib.site-packages.django.contrib.syndication', 'venv.Lib.site-packages.django.contrib.contenttypes',
              'venv.Lib.site-packages.django.contrib.contenttypes.management',
              'venv.Lib.site-packages.django.contrib.contenttypes.migrations', 'venv.Lib.site-packages.django.dispatch',
              'venv.Lib.site-packages.django.template', 'venv.Lib.site-packages.django.template.loaders',
              'venv.Lib.site-packages.django.template.backends', 'venv.Lib.site-packages.django.middleware',
              'venv.Lib.site-packages.django.templatetags', 'venv.Lib.site-packages.openid',
              'venv.Lib.site-packages.openid.store', 'venv.Lib.site-packages.openid.yadis',
              'venv.Lib.site-packages.openid.server', 'venv.Lib.site-packages.openid.consumer',
              'venv.Lib.site-packages.openid.extensions', 'venv.Lib.site-packages.openid.extensions.draft',
              'venv.Lib.site-packages.qrcode', 'venv.Lib.site-packages.qrcode.templatetags',
              'venv.Lib.site-packages.allauth', 'venv.Lib.site-packages.allauth.account',
              'venv.Lib.site-packages.allauth.account.management',
              'venv.Lib.site-packages.allauth.account.management.commands',
              'venv.Lib.site-packages.allauth.account.migrations',
              'venv.Lib.site-packages.allauth.account.templatetags', 'venv.Lib.site-packages.allauth.socialaccount',
              'venv.Lib.site-packages.allauth.socialaccount.providers',
              'venv.Lib.site-packages.allauth.socialaccount.providers.vk',
              'venv.Lib.site-packages.allauth.socialaccount.providers.box',
              'venv.Lib.site-packages.allauth.socialaccount.providers.fxa',
              'venv.Lib.site-packages.allauth.socialaccount.providers.cern',
              'venv.Lib.site-packages.allauth.socialaccount.providers.daum',
              'venv.Lib.site-packages.allauth.socialaccount.providers.line',
              'venv.Lib.site-packages.allauth.socialaccount.providers.xing',
              'venv.Lib.site-packages.allauth.socialaccount.providers.agave',
              'venv.Lib.site-packages.allauth.socialaccount.providers.asana',
              'venv.Lib.site-packages.allauth.socialaccount.providers.auth0',
              'venv.Lib.site-packages.allauth.socialaccount.providers.azure',
              'venv.Lib.site-packages.allauth.socialaccount.providers.baidu',
              'venv.Lib.site-packages.allauth.socialaccount.providers.bitly',
              'venv.Lib.site-packages.allauth.socialaccount.providers.hubic',
              'venv.Lib.site-packages.allauth.socialaccount.providers.kakao',
              'venv.Lib.site-packages.allauth.socialaccount.providers.naver',
              'venv.Lib.site-packages.allauth.socialaccount.providers.oauth',
              'venv.Lib.site-packages.allauth.socialaccount.providers.orcid',
              'venv.Lib.site-packages.allauth.socialaccount.providers.slack',
              'venv.Lib.site-packages.allauth.socialaccount.providers.steam',
              'venv.Lib.site-packages.allauth.socialaccount.providers.vimeo',
              'venv.Lib.site-packages.allauth.socialaccount.providers.weibo',
              'venv.Lib.site-packages.allauth.socialaccount.providers.yahoo',
              'venv.Lib.site-packages.allauth.socialaccount.providers.amazon',
              'venv.Lib.site-packages.allauth.socialaccount.providers.disqus',
              'venv.Lib.site-packages.allauth.socialaccount.providers.douban',
              'venv.Lib.site-packages.allauth.socialaccount.providers.dwolla',
              'venv.Lib.site-packages.allauth.socialaccount.providers.edmodo',
              'venv.Lib.site-packages.allauth.socialaccount.providers.feedly',
              'venv.Lib.site-packages.allauth.socialaccount.providers.flickr',
              'venv.Lib.site-packages.allauth.socialaccount.providers.github',
              'venv.Lib.site-packages.allauth.socialaccount.providers.gitlab',
              'venv.Lib.site-packages.allauth.socialaccount.providers.globus',
              'venv.Lib.site-packages.allauth.socialaccount.providers.google',
              'venv.Lib.site-packages.allauth.socialaccount.providers.mailru',
              'venv.Lib.site-packages.allauth.socialaccount.providers.meetup',
              'venv.Lib.site-packages.allauth.socialaccount.providers.oauth2',
              'venv.Lib.site-packages.allauth.socialaccount.providers.openid',
              'venv.Lib.site-packages.allauth.socialaccount.providers.openid.migrations',
              'venv.Lib.site-packages.allauth.socialaccount.providers.paypal',
              'venv.Lib.site-packages.allauth.socialaccount.providers.reddit',
              'venv.Lib.site-packages.allauth.socialaccount.providers.stripe',
              'venv.Lib.site-packages.allauth.socialaccount.providers.trello',
              'venv.Lib.site-packages.allauth.socialaccount.providers.tumblr',
              'venv.Lib.site-packages.allauth.socialaccount.providers.twitch',
              'venv.Lib.site-packages.allauth.socialaccount.providers.weixin',
              'venv.Lib.site-packages.allauth.socialaccount.providers.discord',
              'venv.Lib.site-packages.allauth.socialaccount.providers.dropbox',
              'venv.Lib.site-packages.allauth.socialaccount.providers.patreon',
              'venv.Lib.site-packages.allauth.socialaccount.providers.persona',
              'venv.Lib.site-packages.allauth.socialaccount.providers.shopify',
              'venv.Lib.site-packages.allauth.socialaccount.providers.spotify',
              'venv.Lib.site-packages.allauth.socialaccount.providers.twitter',
              'venv.Lib.site-packages.allauth.socialaccount.providers.untappd',
              'venv.Lib.site-packages.allauth.socialaccount.providers.basecamp',
              'venv.Lib.site-packages.allauth.socialaccount.providers.coinbase',
              'venv.Lib.site-packages.allauth.socialaccount.providers.doximity',
              'venv.Lib.site-packages.allauth.socialaccount.providers.draugiem',
              'venv.Lib.site-packages.allauth.socialaccount.providers.evernote',
              'venv.Lib.site-packages.allauth.socialaccount.providers.facebook',
              'venv.Lib.site-packages.allauth.socialaccount.providers.linkedin',
              'venv.Lib.site-packages.allauth.socialaccount.providers.telegram',
              'venv.Lib.site-packages.allauth.socialaccount.providers.angellist',
              'venv.Lib.site-packages.allauth.socialaccount.providers.authentiq',
              'venv.Lib.site-packages.allauth.socialaccount.providers.battlenet',
              'venv.Lib.site-packages.allauth.socialaccount.providers.bitbucket',
              'venv.Lib.site-packages.allauth.socialaccount.providers.eveonline',
              'venv.Lib.site-packages.allauth.socialaccount.providers.instagram',
              'venv.Lib.site-packages.allauth.socialaccount.providers.mailchimp',
              'venv.Lib.site-packages.allauth.socialaccount.providers.microsoft',
              'venv.Lib.site-packages.allauth.socialaccount.providers.pinterest',
              'venv.Lib.site-packages.allauth.socialaccount.providers.robinhood',
              'venv.Lib.site-packages.allauth.socialaccount.providers.dataporten',
              'venv.Lib.site-packages.allauth.socialaccount.providers.eventbrite',
              'venv.Lib.site-packages.allauth.socialaccount.providers.foursquare',
              'venv.Lib.site-packages.allauth.socialaccount.providers.jupyterhub',
              'venv.Lib.site-packages.allauth.socialaccount.providers.quickbooks',
              'venv.Lib.site-packages.allauth.socialaccount.providers.salesforce',
              'venv.Lib.site-packages.allauth.socialaccount.providers.soundcloud',
              'venv.Lib.site-packages.allauth.socialaccount.providers.windowslive',
              'venv.Lib.site-packages.allauth.socialaccount.providers.digitalocean',
              'venv.Lib.site-packages.allauth.socialaccount.providers.vimeo_oauth2',
              'venv.Lib.site-packages.allauth.socialaccount.providers.fivehundredpx',
              'venv.Lib.site-packages.allauth.socialaccount.providers.odnoklassniki',
              'venv.Lib.site-packages.allauth.socialaccount.providers.stackexchange',
              'venv.Lib.site-packages.allauth.socialaccount.providers.linkedin_oauth2',
              'venv.Lib.site-packages.allauth.socialaccount.providers.bitbucket_oauth2',
              'venv.Lib.site-packages.allauth.socialaccount.providers.twentythreeandme',
              'venv.Lib.site-packages.allauth.socialaccount.migrations',
              'venv.Lib.site-packages.allauth.socialaccount.templatetags', 'venv.Lib.site-packages.asgiref',
              'venv.Lib.site-packages.automat', 'venv.Lib.site-packages.automat._test',
              'venv.Lib.site-packages.certifi', 'venv.Lib.site-packages.chardet', 'venv.Lib.site-packages.chardet.cli',
              'venv.Lib.site-packages.urllib3', 'venv.Lib.site-packages.urllib3.util',
              'venv.Lib.site-packages.urllib3.contrib', 'venv.Lib.site-packages.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.urllib3.packages', 'venv.Lib.site-packages.urllib3.packages.backports',
              'venv.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'venv.Lib.site-packages.hamcrest',
              'venv.Lib.site-packages.hamcrest.core', 'venv.Lib.site-packages.hamcrest.core.core',
              'venv.Lib.site-packages.hamcrest.core.helpers', 'venv.Lib.site-packages.hamcrest.library',
              'venv.Lib.site-packages.hamcrest.library.text', 'venv.Lib.site-packages.hamcrest.library.number',
              'venv.Lib.site-packages.hamcrest.library.object', 'venv.Lib.site-packages.hamcrest.library.collection',
              'venv.Lib.site-packages.hamcrest.library.integration', 'venv.Lib.site-packages.oauthlib',
              'venv.Lib.site-packages.oauthlib.oauth1', 'venv.Lib.site-packages.oauthlib.oauth1.rfc5849',
              'venv.Lib.site-packages.oauthlib.oauth1.rfc5849.endpoints', 'venv.Lib.site-packages.oauthlib.oauth2',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749.clients',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749.endpoints',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749.grant_types', 'venv.Lib.site-packages.oauthlib.openid',
              'venv.Lib.site-packages.oauthlib.openid.connect', 'venv.Lib.site-packages.oauthlib.openid.connect.core',
              'venv.Lib.site-packages.oauthlib.openid.connect.core.endpoints',
              'venv.Lib.site-packages.oauthlib.openid.connect.core.grant_types', 'venv.Lib.site-packages.requests',
              'venv.Lib.site-packages.sqlparse', 'venv.Lib.site-packages.sqlparse.engine',
              'venv.Lib.site-packages.sqlparse.filters', 'venv.Lib.site-packages.hyperlink',
              'venv.Lib.site-packages.hyperlink.test', 'venv.Lib.site-packages.constantly',
              'venv.Lib.site-packages.defusedxml', 'venv.Lib.site-packages.exampleproj',
              'venv.Lib.site-packages.incremental', 'venv.Lib.site-packages.incremental.tests',
              'venv.Lib.site-packages.crispy_forms', 'venv.Lib.site-packages.crispy_forms.tests',
              'venv.Lib.site-packages.crispy_forms.templatetags', 'venv.Lib.site-packages.async_timeout',
              'venv.Lib.site-packages.widget_tweaks', 'venv.Lib.site-packages.widget_tweaks.templatetags',
              'venv.Lib.site-packages.requests_oauthlib', 'venv.Lib.site-packages.requests_oauthlib.compliance_fixes',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations', 'resume', 'resume.migrations',
              'theme1', 'theme1.migrations', 'Company', 'Company.migrations', 'feeback', 'feeback.migrations',
              'web_demo', 'restaurant', 'restaurant.migrations'],
    url='',
    license='',
    author='ShravaN',
    author_email='shravan2967@gmail.com',
    description='simple theme edior (web builder)'
)
