# Generated by Django 2.2.1 on 2019-05-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
    ]
