# Generated by Django 2.2.1 on 2019-05-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
