# Generated by Django 2.2.1 on 2019-05-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
