# Generated by Django 2.2.1 on 2019-05-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='theme1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('menu1', models.CharField(max_length=25)),
                ('menu2', models.CharField(max_length=25)),
                ('menu3', models.CharField(max_length=25)),
                ('menu4', models.CharField(max_length=25)),
            ],
        ),
    ]
