# Generated by Django 2.2.1 on 2019-05-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme1',
            name='projectname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
