# Generated by Django 2.2.1 on 2019-05-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme1', '0002_theme1_projectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme1',
            name='menu1',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='theme1',
            name='menu2',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='theme1',
            name='menu3',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='theme1',
            name='menu4',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
