# Generated by Django 2.2.1 on 2019-05-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme1', '0003_auto_20190502_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme1',
            name='about',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
