# Generated by Django 2.2.1 on 2019-05-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme1', '0005_theme1_brandimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme1',
            name='about',
        ),
    ]
