# Generated by Django 2.2.1 on 2019-05-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme1', '0006_remove_theme1_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme1',
            name='brandimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
