# Generated by Django 2.2.1 on 2019-05-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme1', '0008_theme1_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme1',
            name='type',
            field=models.CharField(default='Normal Theme', max_length=50),
        ),
    ]
