# Generated by Django 2.2.1 on 2019-05-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20190506_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='restdb',
            name='about',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restdb',
            name='ph_num',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restdb',
            name='review_link',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restdb',
            name='brandimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
