# Generated by Django 2.2.1 on 2019-05-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20190507_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restdb',
            name='gallery1',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='gallery2',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='gallery3',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='gallery4',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='spldish1img',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='spldish1muted',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='spldish1name',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='spldish1price',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='spldish2img',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='spldish2muted',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='spldish2name',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='spldish2price',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='spldish3img',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='spldish3muted',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='spldish3name',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='spldish3price',
        ),
    ]
