# Generated by Django 2.2.1 on 2019-05-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20190507_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restdb',
            name='projectname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
