# Generated by Django 2.2.1 on 2019-05-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20190508_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='restdb',
            name='AppIcon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='restdb',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
