# Generated by Django 2.2.1 on 2019-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20190508_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='restdb',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='restdb',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
