# Generated by Django 2.2.1 on 2019-05-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20190508_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='restdb',
            name='Facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restdb',
            name='Instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restdb',
            name='Twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
