# Generated by Django 2.2.1 on 2019-05-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20190508_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='restdb',
            name='Social_Description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='restdb',
            name='Social_Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='restdb',
            name='Social_Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
