# Generated by Django 2.2.1 on 2019-05-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20190508_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestDbContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Your_Message', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='restdb',
            name='Your_Message',
        ),
    ]
