# Generated by Django 2.2.1 on 2019-05-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20190508_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='restdbcontact',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.RestDb'),
            preserve_default=False,
        ),
    ]
