# Generated by Django 2.2.1 on 2019-05-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_restdbcontact_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='restdbcontact',
            name='essage',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
