# Generated by Django 2.2.1 on 2019-05-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_remove_restdbcontact_essage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restdbcontact',
            name='theme',
        ),
    ]
