# Generated by Django 2.2.1 on 2019-05-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_auto_20190508_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restdbcontact',
            name='theme',
        ),
    ]
