# Generated by Django 2.2.1 on 2019-05-08 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_remove_restdbcontact_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='restdbcontact',
            name='theme',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='restaurant.RestDb'),
        ),
    ]
