# Generated by Django 2.2.1 on 2019-05-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_auto_20190517_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='restdb',
            name='Type',
            field=models.CharField(default='Restaurant', max_length=50),
        ),
    ]
