# Generated by Django 2.2.1 on 2019-05-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_restdb_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='restdb',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
