# Generated by Django 2.2.1 on 2019-05-17 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=50, unique=True)),
                ('Brand_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=10, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Type', models.CharField(default='Company Theme', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
