# Generated by Django 2.2.1 on 2019-05-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_auto_20190517_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydb',
            old_name='Background_Color_Left_Column',
            new_name='Background_Color_About',
        ),
        migrations.RenameField(
            model_name='companydb',
            old_name='Background_Color_Right_Column',
            new_name='Background_Color_Banner',
        ),
        migrations.AddField(
            model_name='companydb',
            name='Background_Color_Navbar',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='companydb',
            name='Background_Color_Service',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
