# Generated by Django 2.2.1 on 2019-05-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_auto_20190517_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydb',
            name='Background_Color_Navbar_Accent_Color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
