# Generated by Django 2.2.1 on 2019-05-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_companydb_background_color_navbar_accent_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydb',
            name='Background_Color_Navbar_Accent_Color',
        ),
    ]
