# Generated by Django 2.2.1 on 2019-05-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resumneDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=50, unique=True)),
                ('Profile_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=10, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('About_Me', models.CharField(blank=True, max_length=2000, null=True)),
                ('Skills', models.CharField(blank=True, max_length=1000, null=True)),
                ('Experience', models.CharField(blank=True, max_length=1000, null=True)),
                ('Upload_Resumne', models.FileField(blank=True, null=True, upload_to='files/')),
                ('Profile_Picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('Instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('Twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('GitHub', models.CharField(blank=True, max_length=100, null=True)),
                ('Background_Color_Left_Column', models.CharField(blank=True, max_length=10, null=True)),
                ('Background_Color_Right_Column', models.CharField(blank=True, max_length=10, null=True)),
                ('Accent_Color', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
