# Generated by Django 2.2.1 on 2019-05-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumnedb',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
